name: ord_dart
version: 0.0.8+1

description: "The Flutter plugin that supports Ordinals protocol (Runes protocol only)."
repository: https://github.com/AstroxNetwork/ord_dart
issue_tracker: https://github.com/AstroxNetwork/ord_dart/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_rust_bridge: '>=2.0.0 <2.1.0'
  freezed_annotation: ^2.2.0
  meta: ^1.12.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  build_runner: ^2.4.4
  ffi: ^2.1.0
  ffigen: ^11.0.0
  freezed: ^2.5.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
